// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byzpfvqjsgjuouawixfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5enBmdnFqc2dqdW91YXdpeGZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MTIwMjAsImV4cCI6MjA2MTQ4ODAyMH0.7QzYzdQ2WxJpyAF3Ne-hO1pvZtaCwrewCANzoVgYps4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);